Repository honestbank/terraform-aws-eks, pull requests merged in 2021-08, with the labels that each got.

#2 chore: remove exposed (revoked) credentials
  README.md
  run.sh
  test/aws-eks_test.go
Labels: size/S

#4 chore: update map_user and map_role
  eks.tf
  test.tfvars
  variables.tf
Labels: size/M

#5 chore: update eks.tf
  eks.tf
  outputs.tf
  test/aws-eks_test.go
Labels: size/M

#6 chore: Update outputs in aws-eks submodule
  eks.tf
  outputs.tf
Labels: size/S

#10 chore: fix issue with eks instance not being detected
  eks.tf
Labels: size/XS

#8 chore: update PR template
  .github/pull_request_template.md
Labels: size/S

#13 chore: Update terratest to point to the right folder
  .github/workflows/terratest.yml
  template.auto.tfvars
  test/aws-eks_test.go
Labels: size/M

#7 ci: add semantic release
  .github/workflows/terratest.yml
  release.config.js
Labels: size/S

#15 test: add k8s provider to eks.tf module
  eks/eks.tf
  template.auto.tfvars
Labels: size/S

#17 chore: add support for IRSA in terraform-aws-eks [ONE-778]
  .github/workflows/terratest.yml
  README.md
  eks/eks.tf
  eks/outputs.tf
  eks/variables.tf
  outputs.tf
  remote-backend.tf
  template.auto.tfvars
  test/aws-eks_test.go
  variables.tf
Labels: size/L
